[package]
name = "libcdio-cli"
version = "0.1.0"
edition = "2024"
authors = ["Shiva Kiran Koninty"]
description = "Utilities to work with CD/DVD media, ISO 9660 and UDF images"
license = "GPL-3.0-or-later"
repository = "https://github.com/libcdio/libcdio-cli"
exclude = ["/tests"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["cargo", "derive"] }
libcdio-rs = { git = "https://github.com/libcdio/libcdio-rs" }
time = { version = "0.3.47", features = ["formatting", "local-offset", "macros"], optional = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[[bin]]
name = "drive-info"
path = "src/drive-info/main.rs"
required-features = ["drive-info"]

[[bin]]
name = "iso-cp"
path = "src/iso-cp/main.rs"
required-features = ["iso-cp"]

[[bin]]
name = "iso-ls"
path = "src/iso-ls/main.rs"
required-features = ["iso-ls"]

[[bin]]
name = "mmc-cli"
path = "src/mmc-cli/main.rs"
required-features = ["mmc-cli"]

[features]
default = ["drive-info", "iso-ls", "iso-cp", "mmc-cli"]
drive-info = ["libcdio-rs/mmc"]
iso-ls = ["libcdio-rs/iso9660", "libcdio-rs/udf", "dep:time"]
iso-cp = ["libcdio-rs/iso9660", "libcdio-rs/udf"]
mmc-cli = ["libcdio-rs/mmc"]

[dev-dependencies]
assert_cmd = { version = "2.2.2", features = ["color"] }
assert_fs = { version = "1.1.4", features = ["color"] }
